unagauchada/config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :buys
  resources :categoria
  resources :gauchadas
  
  get 'index/index'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #ruta de inicio devise
  root to: "index#index"
  #resources :menu 
  get "postularse/new"
  post "postularse/create"
  get "postularse/:id" => "postularse#show", :as => :post
end

unagauchada/app/models/gauchada.rb
class Gauchada < ApplicationRecord
    #un gauchda es publicado por un usuario
	belongs_to :user
	belongs_to :category
	has_attached_file :cover, styles: { medium:"800x800" ,thumb:"200x200" , mini: "50x50"}
	validates_attachment :cover, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }


	#filtrado
	def self.search(search)
		 if search 
  			  where('title LIKE ?', "%#{search}%")

  		else
    		
  		end

	end
end

unagauchada/app/controllers/gauchadas_controller.rb
  class GauchadasController < ApplicationController
  before_action :set_gauchada, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index,:show]
  # GET /gauchadas
  # GET /gauchadas.json
  
  def index
    @busqueda=params[:searchbox]
    @selecion=params[:selecion]
    @order=params[:opcion]
    @opcion="#{@selecion} #{params[:opcion]}"
    
    
    if @busqueda and @selecion
      @gauchadas= Gauchada.search(@busqueda).order(@opcion)
      
    elsif @selecion
      @gauchadas= Gauchada.order(@opcion)
      
    elsif @busqueda
        @gauchadas= Gauchada.search(@busqueda)
    else
      @gauchadas= Gauchada.all
    end
  end


  # GET /gauchadas/1
  # GET /gauchadas/1.json
  def show
  end

  # GET /gauchadas/new
  def new
    @gauchada = Gauchada.new
    
  end

  # GET /gauchadas/1/edit
  def edit
    if @gauchada.cant_postulantes > 0
      respond_to do |format|
        format.html { redirect_to @gauchada, notice: 'No se puede editar porque hay postulantes pendientes.' }
      end
    end
  end

  # POST /gauchadas
  # POST /gauchadas.json
  def create
    if current_user.creditos >= 1
      @gauchada = current_user.gauchadas.new(gauchada_params)

      respond_to do |format|
        if @gauchada.save
          @credito=current_user.creditos - 1
          current_user.update_column(:creditos, @credito )
          format.html { redirect_to @gauchada, notice: 'Gauchada Creada con éxito.' }
          format.json { render :show, status: :created, location: @gauchada }
        else
          format.html { render :new }
          format.json { render json: @gauchada.errors, status: :unprocessable_entity }
        end
      end
    else
      respond_to do |format|
        format.html { redirect_to '/buys/new', notice: 'Ud no posee credito para realizar la compra.' }
      end
    end
  end

  # PATCH/PUT /gauchadas/1
  # PATCH/PUT /gauchadas/1.json
  def update
    respond_to do |format|
      if @gauchada.update(gauchada_params)
        format.html { redirect_to @gauchada, notice: 'Gauchada acutalizada correctamente.' }
        format.json { render :show, status: :ok, location: @gauchada }
      else
        format.html { render :edit }
        format.json { render json: @gauchada.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gauchadas/1
  # DELETE /gauchadas/1.json
  def destroy
    if @gauchada.cant_postulantes > 0
      respond_to do |format|
        format.html { redirect_to @gauchada, notice: 'No se puede eliminar porque hay postulantes.' }
      end
    else
      @user=@gauchada.user
      @user.creditos= @user.creditos + 1
      @user.save
      @gauchada.destroy
      respond_to do |format|
        format.html { redirect_to gauchadas_url, notice: 'Gauchada eliminada.' }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gauchada
      @gauchada = Gauchada.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gauchada_params
      params.require(:gauchada).permit(:nombre, :title, :descripcion, :estado, :fecha_de_inicio, :fecha_limite, :cover, :ciudad,:buscar)
    end
end

unagauchada/app/helpers/gauchadas_helper.rb
module GauchadasHelper
end

unagauchada/app/views/gauchadas/_form.html.erb
<div class="form-group" id="show_gauchadas" >
<%= form_for gauchada, :html => {:class => 'form_group'} do |f| %>
  <% if gauchada.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(gauchada.errors.count, "error") %> prohibited this gauchada from being saved:</h2>

      <ul>
      <% gauchada.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 

  <div class="field">
    <%= f.label :title  %> <br>
    <%= f.text_field :title, :required => true, :class  => 'form_control' %>
  </div>

  <div class="field">
    <%= f.label :descripcion %> <br>
    <%= f.text_area :descripcion, :required => true, :class  => 'form_control', :cols => 25, :rows => 10 %>
  </div>
  <div class="field">
  <%= f.label "Imagen" %> <br/>
 <%= f.file_field :cover %>
  </div>
  <div class="field"><br>
    <%= f.label :ciudad %>
    <%= f.text_field :ciudad, :required => true, :class  => 'form_control' %>
    <br>
  </div>


  <div class="field"> 
    <%= f.label :fecha_limite %>
    <%= f.date_select :fecha_limite, :required => true %>
    <br>
  </div>

  <div class="actions">
    <%= f.submit 'Enviar',  :class => 'btn btn-default' %>
  </div>
</div>
<% end %>

unagauchada/app/views/gauchadas/_show_all_gauchadas.html.erb
<div class="filters">
<p id="notice" ><%= notice %></p>
<div id="container" >

<form role="search" method="get" id="searchform" action="/gauchadas" >
  <label for="s">
    <i class="icon-search"></i>
  </label>
  <input type="text" value="<%=@busqueda%>" placeholder="Buscar" class="" name="searchbox" id="s" />

</form>
</div>
  <% if @gauchadas.empty?%>
  <%= "No hay resultados" %>
  <%end%>
  </div>
      <form action="/gauchadas" class="form_order" method="get"> 
        <SELECT NAME="selecion">
        <%if @selecion=="title" %> 
           <OPTION VALUE="title"selected>Titulo</OPTION> 
        <%else%>
           <OPTION VALUE="title">Titulo</OPTION>
          <%end%>
        <%if @selecion=="cant_postulantes" %>
           <OPTION VALUE="cant_postulantes"selected>Postulante</OPTION>
        <%else%>
           <OPTION VALUE="cant_postulantes">Postulante</OPTION>
           <%end%>
        <%if @selecion=="created_at"%> 
           <OPTION VALUE="created_at"selected>Cronologicamente</OPTION>
           <%else%>
             <OPTION VALUE="created_at">Cronologicamente</OPTION>
           <%end%>
        </SELECT>
        <SELECT NAME="opcion" SIZE="1">
          <%if @order=="ASC" %>
           <OPTION VALUE="ASC"selected>Ascendente</OPTION> 
           <%else%>
            <OPTION VALUE="ASC">Ascendete</OPTION> 
            <%end%>
          <%if @order=="DESC"%>
           <OPTION VALUE="DESC"selected>Descendete</OPTION> 
           <%else%>
           <OPTION VALUE="DESC">Descendete</OPTION>
           <%end%>

        </SELECT> 
        <input type="hidden" name="searchbox" value="<%=@busqueda%>">
       
        <input class="filtrar" TYPE="submit" value="Ordenar">
       </form>

    <% @gauchadas.each do |gauchada| %>
    <%if gauchada.fecha_limite > Date.today %>
            <div class="contenedor_guchada">
            <h2 class="titulo_gauchadas"><%= gauchada.title %></h2>
            <div class="imagen_gauchadas">
            <% if gauchada.cover_file_size.nil? %>
                    <img src="assets/avatar.png">
                <% else %>
                    <%= image_tag gauchada.cover.url('thumb') %>
                <% end %>
            </div>
            <p class="descripcion_gauchadas"><%= gauchada.descripcion %></p>
            <strong>
            <br>
            <p>Postulados: <%= gauchada.cant_postulantes
             %></p>
            <p>Categoria: <%= gauchada.category.nombre %> </p>
            <p>Ciudad: <%= gauchada.ciudad %></p>
            <p class="fecha_limite_gauchada">Fecha limite: <%= gauchada.fecha_limite %></p></strong>
            <div class="clear_gauchadas">
            <%= link_to 'Ver ', gauchada, :class => "link_gauchadas" %>
            <% if user_signed_in? %>
                <% if current_user.id == gauchada.user.id %>
                    <%= link_to 'Editar', edit_gauchada_path(gauchada), :class => "link_gauchadas" %>
                    <%= link_to 'Eliminar', gauchada, :class => "link_gauchadas", method: :delete, data: { confirm: '¿Estas seguro?' } %>
                <% else %>

                  <%= link_to 'Postularse', {controller:"postularse", action:"new", id_gauchada: gauchada.id}, :class => "link_gauchadas"%>    
                <% end %>
              <%else%>
                <%= link_to 'Postularse', {controller:"postularse", action:"new", id_gauchada: gauchada.id}, :class => "link_gauchadas"%>    
              <%end%>
            
            <%=  
           render 'postularse/show'  %>
            <p class="by_autor" >Por: <a  href="#"><%= gauchada.user.nombre %> <%= gauchada.user.apellido %></a>
            </p>
            </div> 
            </div>
            <% end %>
          </article> 

        <br>
    <% end %>

unagauchada/app/views/gauchadas/_show_all_gauchadas2.html.erb
<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Title</th>
      <th>Descripcion</th>
      <th>Estado</th>
      <th>Fecha de inicio</th>
      <th>Fecha limite</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @gauchadas.each do |gauchada| %>
      <tr>
        <td><%= gauchada.nombre %></td>
        <td><%= gauchada.title %></td>
        <td><%= gauchada.descripcion %></td>
        <td><%= gauchada.estado %></td>
        <td><%= gauchada.fecha_de_inicio %></td>
        <td><%= gauchada.fecha_limite %></td>
        <td><%= link_to 'Show', gauchada %></td>
        <td><%= link_to 'Edit', edit_gauchada_path(gauchada) %></td>
        <td><%= link_to 'Destroy', gauchada, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

unagauchada/app/views/gauchadas/edit.html.erb
<br><br><br>
<h1 class="titulos_sesion">Editar Gauchada</h1>

<%= render 'form', gauchada: @gauchada %>
<br>
<%= link_to 'Ver gauchada', @gauchada,:class => 'link_gauchadas' %> 
<%= link_to 'Ver todas las gauchadas', gauchadas_path, :class => 'link_gauchadas' %>

unagauchada/app/views/gauchadas/index.html.erb
<br><br><br>
<h1 class="titulos_sesion">Todas las Gauchadas</h1>
<br>
<section class="home_gauchadas">

<%= 
   render 'gauchadas/show_all_gauchadas'  %>

<%= link_to 'Nueva gauchada', new_gauchada_path, :class => 'link_gauchadas' %>
<p id="notice"><%= notice %></p>
</section>

unagauchada/app/views/gauchadas/new.html.erb
 <br><br><br>
<h1 class="titulos_sesion">Nueva Gauchada</h1>
<%= render 'form', gauchada: @gauchada %>
<br>
<%= link_to 'Todas las gauchadas', gauchadas_path, :class => 'link_gauchadas' %>

unagauchada/app/views/gauchadas/show.html.erb
<br><br><br>
<div class="show_gauchada">
<p class="postulantes_gauchada">
   <strong>Cantidad de postulantes:</strong>
   <%= @gauchada.cant_postulantes %>
</p>
<h2 class="title_gauchada titulo_gauchadas">
  <%= @gauchada.title %>
</h2>

<div class="field imagen_gauchada">
 <% if @gauchada.cover_file_size.nil? %>
 <img src="/assets/avatar.png">
 <% else %>
 <%= image_tag @gauchada.cover.url('thumb') %>
 <% end %>
 </div>

<p class="descripcion_gauchada">
  <%= @gauchada.descripcion %>
</p>


<div class="fecha_gauchada">
  <strong>Fecha limite:</strong>
  <%= @gauchada.fecha_limite %>
</div>


<p class="ciudad_gauchada">
   <strong>Ciudad:</strong>
   <%= @gauchada.ciudad %>
</p>
<p class="">
  <strong>Categoria:</strong>
  <%= @gauchada.categorium.nombre %>
</p>


<%= link_to 'Volver', gauchadas_path, :class => "link_gauchadas" %>

<% if user_signed_in? %>
  <% if current_user.id == @gauchada.user.id %>
        <%= link_to 'Editar', edit_gauchada_path(@gauchada), :class => "link_gauchadas" %>
        <%= link_to 'Eliminar', @gauchada, :class => "link_gauchadas", method: :delete, data: { confirm: '¿Estas seguro?' } %>
  <%else%>      
  <%= link_to 'Postularse', {controller:"postularse", action:"new", id_gauchada: @gauchada.id}, :class => "link_gauchadas"%>
  <% end %>
<%else%>      
  <%= link_to 'Postularse', {controller:"postularse", action:"new", id_gauchada: @gauchada.id}, :class => "link_gauchadas"%>
<% end %>
<strong><p class="autor_gauchada by_autor">Por: <a  href="#"><%= @gauchada.user.nombre %> <%= @gauchada.user.apellido %></a> </p></strong>
<p id="notice"><%= notice %></p>
</div>