unagauchada/config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :buys
  resources :categoria
  resources :gauchadas
  
  get 'index/index'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #ruta de inicio devise
  root to: "index#index"
  #resources :menu 
  get "postularse/new"
  post "postularse/create"
  get "postularse/:id" => "postularse#show", :as => :post
end

unagauchada/app/models/buy.rb
class Buy < ApplicationRecord
	 belongs_to :user
end

unagauchada/app/controllers/buys_controller.rb
class BuysController < ApplicationController
  before_action :set_buy, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /buys
  # GET /buys.json
  def index
    @buys = Buy.all
  end

  # GET /buys/1
  # GET /buys/1.json
  def show
  end

  # GET /buys/new
  def new
    @buy = Buy.new
  end

  # GET /buys/1/edit
  def edit
  end

  # POST /buys
  # POST /buys.json
  def create
    @buy = Buy.new(buy_params)
    @tarjetas= Card.all
    @numero= @buy.numero_de_tarjeta 
    #@tarjeta=@tarjetas.first
    @tarjeta = @tarjetas.find_by(numero: @numero)
    @precio_total= @buy.cantidad * 50
    unless @tarjeta.nil?
      if @tarjeta.credito >= @precio_total
            @buy.precio_actual=50
            @buy.precio_total=@precio_total
            @tarjeta.credito= @tarjeta.credito - @precio_total 
            
            @buy.user_id=current_user.id
            current_user.creditos=current_user.creditos + @buy.cantidad
            
            respond_to do |format|
              if @buy.save and current_user.save and @tarjeta.save
                format.html { redirect_to @buy, notice: 'Se ha realizado la compra con éxito.' }
                format.json { render :show, status: :created, location: @buy }
              else
                format.html { render :new }
                format.json { render json: @buy.errors, status: :unprocessable_entity }
              end
            end
        else
          respond_to do |format|
          format.html { redirect_to '/buys/new', notice: 'Crédito insuficiente.' }
        end
        end
      else
        respond_to do |format|
        format.html { redirect_to '/buys/new', notice: 'Tarjeta invalida.' }
       end
  end
end
  # PATCH/PUT /buys/1
  # PATCH/PUT /buys/1.json
  def update
    respond_to do |format|
      if @buy.update(buy_params)
        format.html { redirect_to @buy, notice: 'Buy was successfully updated.' }
        format.json { render :show, status: :ok, location: @buy }
      else
        format.html { render :edit }
        format.json { render json: @buy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /buys/1
  # DELETE /buys/1.json
  def destroy
    @buy.destroy
    respond_to do |format|
      format.html { redirect_to buys_url, notice: 'Buy was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_buy
      @buy = Buy.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def buy_params
      params.require(:buy).permit(:cantidad, :precio_total, :precio_actual, :fecha, :numero_de_tarjeta)
    end
end

unagauchada/app/helpers/buys_helper.rb
module BuysHelper
end

unagauchada/app/views/buys/_form.html.erb
<div class="form-group" id="buy_new" >
<%= form_for(buy) do |f| %>
  <% if buy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(buy.errors.count, "error") %> prohibited this buy from being saved:</h2>

      <ul>
      <% buy.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cantidad %>
    <%= f.number_field :cantidad, :min => 1, :class => '.form-control' %>
  </div>
  <div class="field">
  <%= f.label :numero_de_tarjeta%>
  <%= f.text_field :numero_de_tarjeta,  :class => '.form-control'%>
  </div>
  <div><p><strong>Precio acutal: </strong>$50</p></div>
  <div class="actions">
    <%= f.submit 'Realizar Compra', :class => 'btn btn-default' %>
  </div>
<% end %>
<%= link_to 'Volver al inicio', '/', :class => 'link_gauchadas' %>
<p id="notice"><%= notice %></p>
</div>

unagauchada/app/views/buys/edit.html.erb
<h1>Editing Buy</h1>

<%= render 'form', buy: @buy %>

<%= link_to 'Show', @buy %> |
<%= link_to 'Back', buys_path %>

unagauchada/app/views/buys/index.html.erb
<br><br><br>
<h1 class="titulos_sesion">Compras</h1>

<table>
  <thead>
    <tr>
      <th>Cantidad</th>
      <th>Precio total</th>
      <th>Precio actual</th>
      <th>Fecha</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @buys.each do |buy| %>
      <tr>
        <td><%= buy.cantidad %></td>
        <td><%= buy.precio_total %></td>
        <td><%= buy.precio_actual %></td>
        <td><%= buy.fecha %></td>
        <td><%= link_to 'Show', buy %></td>
        <!--<td><%= link_to 'Edit', edit_buy_path(buy) %></td>
        <td><%= link_to 'Destroy', buy, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<p id="notice"><%= notice %></p>
<%= link_to 'Nueva compra', new_buy_path, :class => 'link_gauchadas' %>

unagauchada/app/views/buys/new.html.erb
<br><br><br>
<h1 class="titulos_sesion">Nueva compra</h1>

<%= render 'form', buy: @buy %>

unagauchada/app/views/buys/show.html.erb
<br><br><br>
<div class="form-group" style=" margin-left: 40%; margin-top: 150px;"><p>
  <strong>Cantidad:</strong>
  <%= @buy.cantidad %>
</p>

<p>
  <strong>Precio total:</strong>
  <%= @buy.precio_total %>
</p>

<p>
  <strong>Precio actual:</strong>
  <%= @buy.precio_actual %>
</p>
<p id="notice"><%= notice %></p>
<%= link_to 'Nueva Gauchada', '/gauchadas/new', :class => 'link_gauchadas' %>
<%= link_to 'Volver al inicio', '/', :class => 'link_gauchadas' %>
</div>